### PR TITLE
Enable testing; no docker tests

### PR DESCRIPTION
**Pull request by danpetry**

### CODE REVIEW

**Review by skupr-anaconda — APPROVED** [review]
Ah, I see. Great!

**Comment by skupr-anaconda** [comment]
One test failed on `osx-arm64`:
```
not ok 1 - sshd-test_ssh2
/private$SRC_DIR/tests/test_sshd.test: line 130: 64788 Segmentation fault: 11  "${test}"
not ok 2 - sshd-test_auth_pubkey_ok_ed25519
```

**Comment by danpetry** [comment]
Cool, let's see how serious/relevant the test failures are.

**Comment by danpetry** [comment]
The sshd tests were using /usr/bin/ssh and /usr/bin/sshd, which is outside the environment and who knows what can happen, on osx a segfault and on win it wasn't finding required directories. We don't have openssh conda packages apart from a CDT package for linux-aarch64. So just skipped the test. There's a simple test running which should cover basic functionality.

**Comment by danpetry** [comment]
Feel free to merge it yourself if you're happy with it :)

**Comment by skupr-anaconda** [comment]
Thanks, Daniel!

**Pull request merged**
