### PR TITLE
Build with OpenSSL 3

### PR DESCRIPTION
**Pull request by JeanChristopheMorinPerso**
Rebuild using OpenSSL 3.

### CODE REVIEW

**Review by markan — APPROVED** [review]
Looks reasonable to me.

**Review by cbouss — APPROVED** [review]

**Comment by JeanChristopheMorinPerso** [comment]
I have one question before merging. I see openssl isn't specified as a runtime dependency, but when I install libssh2, I clearly see that openssl is pulled in. Should we make the openssl dependency explicit?

**Comment by cbouss** [comment]
> I have one question before merging. I see openssl isn't specified as a runtime dependency, but when I install libssh2, I clearly see that openssl is pulled in. Should we make the openssl dependency explicit?

Good idea.

On a side note, I would wait to merge that openssl3 is actually pushed to defaults.

**Review by varlackc — COMMENTED** [review]
We might want to remove the `abs.yaml` file before merging to defaults.

**Pull request merged**
